import { Gist } from '@/components/Gist';

export const fakeGists: Gist[] = [
  {
    id: '1',
    userId: 'user456',
    username: 'jane_smith',
    name: 'Sample Object 2',
    description: 'This is the second sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2022-08-26',
    created: '2022-08-25',
  },
  {
    id: '2',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '3',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '4',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '5',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '6',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '7',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '8',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '9',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
  {
    id: '10',
    userId: 'user789',
    username: 'sam_jackson',
    name: 'Sample Object 3',
    description: 'This is the third sample object',
    formula: ['function sayHi(greeting) {', '  console.log(greeting);', '}'],
    updated: '2021-08-26',
    created: '2021-08-25',
  },
];
