name: Ping API
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Send Ping Request
        run: |
          response=$(curl -sSf -w "HTTP %{http_code}" https://onxgists.azurewebsites.net/ping)
          echo $response
