name: Ping API
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  ping-client:
    runs-on: ubuntu-latest
    steps:
      - name: Send request
        run: curl -LI https://onxgists.stevanfreeborn.com/ -o /dev/null -w '%{http_code}\n' -s
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: curl -LI https://onxgists.azurewebsites.net/ping -o /dev/null -w '%{http_code}\n' -s
